name: Feature Request
description: No, i won't add 6K/etc to the engine, stop asking for it.
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: What feature do you want to get added on the **base** engine?
    validations:
      required: true
  - type: dropdown
    id: eyetest
    attributes:
      label: To test your sight, and reliability, please select the option of what should NOT be requested.
      options:
        - Thing that would not cause problems
        - Useful feature
        - Actual feedback
        - A good idea
        - 6K+ support
        - Code optimization that would make the game faster. (You should make a PR if this is your request, by the way.)
    validations:
      required: true
